version: 2

aliases:
  - &restore_yarn_cache
    keys:
      - v1-yarn-deps-{{ checksum "yarn.lock" }}
  - &save_yarn_cache
    paths:
      - ~/.cache/yarn
    key: v1-yarn-deps-{{ checksum "yarn.lock" }}

defaults: &defaults
  working_directory: ~/after-work.js
  docker:
    - image: circleci/node:8-stretch-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run: yarn
      - save_cache: *save_yarn_cache

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run: yarn
      - run: yarn lint

  test-node:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run: yarn
      - run: yarn test:node

  test-chrome:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run: yarn
      - run: yarn test:chrome

  test-protractor:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run: yarn
      - run: yarn test:protractor --chromeDriver /usr/local/bin/chromedriver

  test-puppeteer:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run: yarn
      - run: yarn test:puppeteer

  test-node-coverage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run: yarn
      - run: yarn test:coveralls
      - store_artifacts:
          path: ./coverage

workflows:
  version: 2
  all:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test-node:
          requires:
            - install
      - test-chrome:
          requires:
            - install
      - test-protractor:
          requires:
            - install
      - test-puppeteer:
          requires:
            - install
      - test-node-coverage:
          requires:
            - install
